[package]
name = "computorv1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.3"

[[bin]]
name = "computorv1"
path = "src/main.rs"

[lib]
name = "computorv1"
path = "src/lib.rs"

